name: CI pipeline

on:
  push: 
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: install deps
        run: npm ci

      - name: build project
        run: npm run build

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      
      - name: build and push docker image
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/divyanshu3020/izara-ai:latest

          
      - name: trigger render deployment
        run: |
          curl -X POST https://api.render.com/deploy/srv-d8a9b03bc2fs73froqu0?key=hL8Yw5Ttzw8